version: '3'
services:
  download_image_url:
    image: crawler_selenium:latest
    build: ..
    volumes:
    - /etc/localtime:/etc/localtime
    - /tmp/.X11-unix:/tmp/.X11-unix
    - ${SOURCE_CODE_DIR}:/app/
    entrypoint: ["python3", "onemanhua.py"]
#    entrypoint: ["/bin/bash"]

    environment:
    - DISPLAY=$DISPLAY
    - QT_X11_NO_MITSHM=1
    - HIDE_BROWSER=NO
    stdin_open: true
    tty: true
